flipt-io/flipt-client-sdks

- flipt-client-node/README.md
- flipt-client-node/src/evaluation.test.ts
- flipt-client-node/src/index.ts
I think this reads nicer, as at the end of the day, the user shouldnt really have to know about the 'engine' under the hood
> feat(breaking): update node client to use close method instead of freeEngine

- .github/workflows/build-engine.yml
- .github/workflows/test-engine.yml
- flipt-engine/Cargo.toml
- go.work.sum
getting cross compiliation/packaging of engine for multiple architectures
currently, this builds and zips up the engine for the following os/architectures:
- linux/x86_64
- linux/arm64
- mac/arm64
The plan is to integrate this with #35 or similar so that the process is
- use https://github.com/softprops/action-gh-release or release please to create release
- this workflow will then build the lib for the various architectures and upload them to the new release
- we'll then have another workflow download these uploaded zip files and package each of the clients in preparation for publishing
> chore: package/cross-compile

- .gitignore
- build/main.go
- flipt-client-node/package.json
- flipt-client-ruby/flipt-client-ruby.gemspec
- flipt-client-ruby/lib/flipt_client.rb
- flipt-client-ruby/lib/flipt_client/version.rb
- flipt-client-ruby/spec/evaluation_spec.rb
- test/main.go
re: #38 for Ruby
- Updates build pipeline to specify specific languages
- Updates build pipeline to allow push
- Setup push to rubygems registry for Ruby
I tested this by setting up `gitea` locally and configuring it to act as the gem host: https://docs.gitea.com/usage/packages/rubygems/
This pipeline will require updating once we want to push to actual ruby gems, but its good enough for now
> chore: setup build/push workflow for ruby

- Makefile
- build/main.go
Re: #38 
Adds (private) go module push support
Note: This will probably need to change once we push to github. This will probably follow the same process that we use for our existing Go SDK.
Also need to setup the vanity import for this as well
/cc @GeorgeMac
> chore: push go module to gitea

- .github/workflows/package-engine.yml
- README.md
- flipt-client-ruby/Gemfile.lock
- flipt-client-ruby/loadtest.rb
- flipt-engine/Cargo.toml
- test/main.go
s- small readme update
- ~~dont build `rlib` (Rust shared library) for now~~ see: https://github.com/rust-lang/rust/issues/19680
- strip dlls of build/debug symbols for smaller size
Saves about 2MB on MacOS, havent tried on linux yet
```
-rw-r--r--  1 markphelps  staff   780B Dec 26 19:30 libfliptengine.d
-rwxr-xr-x  1 markphelps  staff    10M Dec 26 19:30 libfliptengine.dylib
workspace/client-sdks - [readme-rlib●] » strip -x flipt-client-ruby/lib/ext/darwin_arm64/libfliptengine.dylib
workspace/client-sdks - [readme-rlib●] » ls -lah flipt-client-ruby/lib/ext/darwin_arm64/
total 17024
drwxr-xr-x  4 markphelps  staff   128B Dec 26 19:30 .
drwxr-xr-x  4 markphelps  staff   128B Dec 26 19:27 ..
-rw-r--r--  1 markphelps  staff   780B Dec 26 19:30 libfliptengine.d
-rwxr-xr-x  1 markphelps …
```
> chore: update Readme; rm rlib; strip libraries

- build/main.go
- flipt-client-go/LICENSE
- flipt-client-go/evaluation.go
- flipt-client-node/LICENSE
- flipt-client-python/LICENSE
- flipt-client-ruby/LICENSE
- rm unused flags from build script
- update godocs in go sdk
- copy licenses to each sdk
- use `index-filter` when copying go SDK to own repo as should be faster
> chore: update go sdk godocs; add licenses to all

- .github/workflows/test-engine.yml
- flipt-client-python/flipt_client/__init__.py
- flipt-engine/src/error/mod.rs
- flipt-engine/src/parser/mod.rs
We are using an empty dictionary for the default value of `EngineOpts` currently which will cause the call to the FFI layer to fail if the user doesn't actual provide real values for `EngineOpts`, and the default is used.
This change uses an actual instance of `EngineOpts` as the default.
> fix: instead of using empty dictionary use actual EngineOpts instance

- flipt-engine/examples/evaluation.rs
- flipt-engine/lib/evaluation/src/lib.rs
- flipt-engine/lib/evaluation/src/store/mod.rs
- flipt-engine/src/lib.rs
Fixes: #95 
- Modifies the `Snapshot::build` to propagate any errors instead of returning an empty Document
We still swallow the error in `replace_snapshot`, and will need to figure out what we want to do here, likely something related to #60 
This also returns an error on first call to `new_snapshot_evaluator` at engine initialization if it can't do the first call to get the snapshot from the API, which I think is likely the behavior we want for now
> fix: dont wipe out snapshot if error in parser

- flipt-client-node/README.md
- flipt-client-node/package-lock.json
- flipt-client-node/package.json
- flipt-client-node/src/index.ts
- flipt-client-node/tsconfig.json
set `strict: true` in tsc compiler options for maximum compatibility
https://dev.to/jsdev/strict-mode-typescript-j8p
> chore: use strict compilerOptions for flipt-node

- flipt-client-go/README.md
- flipt-client-go/evaluation.go
- flipt-client-go/evaluation_test.go
- flipt-client-go/models.go
- flipt-client-node/README.md
- flipt-client-node/src/evaluation.test.ts
- flipt-client-node/src/index.ts
- flipt-client-node/src/models.ts
- flipt-client-python/README.md
- flipt-client-python/flipt_client/__init__.py
- flipt-client-python/flipt_client/models.py
- flipt-client-python/tests/__init__.py
- flipt-client-ruby/README.md
- flipt-client-ruby/spec/evaluation_spec.rb
- flipt-engine-ffi/examples/evaluation.rs
- flipt-engine-ffi/src/lib.rs
- flipt-evaluation/src/parser/mod.rs
This PR adds support for substitutable authentication methods. The purpose of this is for the client to either provide a Bearer or JWT token.
Completes FLI-763
> feat(authentication): add support for substitutable authentication methods

- flipt-evaluation/src/parser/mod.rs
Fix the camel casing of jwt token, and add tests for correctness of enum.
> chore(authentication): fix camelcasing of jwt token

- flipt-client-go/evaluation.go
- flipt-client-go/evaluation_test.go
- flipt-client-go/models.go
- flipt-client-node/src/evaluation.test.ts
- flipt-client-node/src/index.ts
- flipt-client-node/src/models.ts
- flipt-client-python/flipt_client/__init__.py
- flipt-client-python/flipt_client/models.py
- flipt-client-python/tests/__init__.py
- flipt-client-ruby/lib/flipt_client.rb
- flipt-client-ruby/spec/evaluation_spec.rb
- flipt-engine-ffi/src/lib.rs
- flipt-evaluation/src/lib.rs
- flipt-evaluation/src/models/common.rs
Add batch evaluation to engine + clients.
This was missing previously, so we are adding it for users to be able to leverage the batch evaluation functionality.
> feat(client-sdks): add batch evaluation to engine

- flipt-client-java/README.md
- flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
- flipt-client-java/src/test/java/TestFliptEvaluationClient.java
java rename shutdown to close to be consistent with other libs; add close to Java example
> chore(breaking): java rename shutdown to close to be consistent

- flipt-client-go/evaluation.go
Based on https://go.dev/blog/cgo#strings-and-things
> go cleanup memory after use

- flipt-client-go/evaluation.go
- flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
- flipt-client-node/src/index.ts
- flipt-client-python/flipt_client/__init__.py
- flipt-client-ruby/lib/flipt_client.rb
- flipt-engine-ffi/src/lib.rs
todos:
> [CString::into_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw) The pointer which this function returns must be returned to Rust and reconstituted using [CString::from_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) to be properly deallocated. Specifically, one should not use the standard C free() function to deallocate this string.
> fix(engine-ffi): prevent memory leaks

- flipt-client-node/README.md
- go.work.sum
Fixes: #169 
Adds note about running with `--pool=forks` flag in vitest
cc @SamuelCabralCruz
> chore: add note about vitest issues

- flipt-evaluation/src/lib.rs
Fixes https://github.com/flipt-io/flipt/issues/2890
@markphelps observed some suspicious casting during evaluation https://github.com/flipt-io/flipt/issues/2890#issuecomment-2016474104
After a bit of reproduction we demonstrated a large error rate when the resulting hash is cast as i32.
`crc32fast::hash(...)` produces a `u32`, which when cast as an `i32` can and does (I checked) wrap around and become negative. This appears to be the cause to the unexpected distribution.
> fix(flipt-evaluation): stop casting crc32 checksum as i32

- flipt-evaluation/src/lib.rs
See: https://github.com/flipt-io/flipt/issues/2890#issuecomment-2016430657
This brings our Rust implementation inline with our Go implementation of search.
> fix(flipt-evaluation): increment bucket search index by one

- Cargo.toml
- flipt-engine-ffi/Cargo.toml
See: https://github.com/flipt-io/flipt-client-sdks/issues/187#issuecomment-2021141830
https://doc.rust-lang.org/cargo/reference/profiles.html#profiles
> Cargo only looks at the profile settings in the Cargo.toml manifest at the root of the workspace. Profile settings defined in dependencies will be ignored.
Which now I understand / see these warnings: https://github.com/flipt-io/flipt-client-sdks/actions/runs/8438700013/job/23111503420#step:5:8
We'll have to create a new engine release and new Go SDK release once this is merged.
> fix(ffi): strip release libraries for real

- flipt-engine-ffi/src/evaluator/mod.rs
Sooner or later this should be fixed. 
```
thread '<unnamed>' panicked at flipt-engine-ffi/src/lib.rs:205:74:
called `Result::unwrap()` on an `Err` value: Server("failed to make request: error sending request for url (http://localhost:8080/internal/v1/evaluation/snapshot/namespace/default)")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
SIGABRT: abort
```
The idea is to start with empty state and use `replace_snapshot` logic to fill it.  If the service isn't available the error will be returned until the service is live and state is updated.
> fix(ffi): prevent fatal error if there is the connection error during client creation

- CONTRIBUTING.md
- flipt-client-browser/README.md
- flipt-client-go/README.md
- flipt-client-java/README.md
- flipt-client-node/README.md
- flipt-client-python/README.md
- flipt-client-ruby/README.md
- flipt-engine-ffi/CHANGELOG.md
- flipt-engine-wasm/README.md
- test/fixtures/testdata/features.yml
minor updates mostly to READMEs so that they make more sense if they are used as the front page on the registries, such as https://www.npmjs.com/package/@flipt-io/flipt-client-browser
> chore: update readmes and fmt with prettier

- release-please-config.json
idk why but I'd like to have the flipt-engine-wasm component version handled by release-please as well
> chore: add back wasm to release-please

- flipt-client-ruby/lib/flipt_client.rb
Hello,
When using [flipt-grpc-ruby](https://github.com/flipt-io/flipt-grpc-ruby/tree/v1.12.0) and flipt_client together, there is an issue where the `Flipt::EvaluationClient` cannot be instantiated. This occurs because flipt-grpc-ruby creates a namespace called [`Flipt::Flipt`](https://github.com/flipt-io/flipt-grpc-ruby/blob/v1.12.0/lib/flipt_services_pb.rb#L8), causing the `Flipt::NoAuthentication` declared in the context of `Flipt::EvaluationClient` to be misinterpreted as `Flipt::Flipt::NoAuthentication`.
To resolve this issue, I removed the `Flipt::` prefix, ensuring that the correct `NoAuthentication` class is selected. This allows `Flipt::EvaluationClient` to be instantiated successfully when using flipt-grpc-ruby and flipt_client together.
Removed the `Flipt::` prefix to resolve …
> No explicit Flipt namespace

- flipt-client-ruby/lib/flipt_client/version.rb
> chore: bump ruby sdk version

- .github/workflows/package-ffi-engine.yml
- .github/workflows/package-ffi-sdks.yml
- README.md
- build/ffi/main.go
- flipt-client-go/README.md
- flipt-client-go/evaluation.go
- flipt-client-java/README.md
- flipt-client-node/README.md
- flipt-client-node/src/index.ts
- flipt-client-python/README.md
- flipt-client-python/flipt_client/__init__.py
- flipt-client-ruby/.rubocop.yml
- flipt-client-ruby/README.md
- flipt-client-ruby/lib/flipt_client.rb
> feat: support intel macs

- .github/workflows/lint-sdks.yml
- flipt-client-node/README.md
- flipt-client-node/package-lock.json
- flipt-client-node/package.json
- flipt-client-node/src/index.ts
> chore(node): try @2060.io/ffi-napi fork as alternative to original ffi-napi

- flipt-engine-ffi/src/evaluator/mod.rs
- flipt-engine-ffi/src/parser/http.rs
- flipt-evaluation/src/error/mod.rs
- flipt-evaluation/src/parser/mod.rs
- flipt-evaluation/src/store/mod.rs
> fix(engine-ffi): return error to caller on connection or parse json failures

- flipt-client-node/package-lock.json
- flipt-client-node/package.json
- flipt-client-node/tsconfig.json
Fixes packaging issue where `src` was getting put at `dist/src` which would then fail to load as well as fail relative imports of engine
> fix: node sdk paths

- .github/workflows/release-please.yml
Google has deprecated [google-github-actions/release-please-action ](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file)repo and moved all activity into new repo.
https://github.com/flipt-io/flipt-client-sdks/actions/runs/9067151077/job/24911609980
> ci: switch to googleapis/release-please-action

- flipt-client-python/pyproject.toml
**Validation**
Ran tests locally and they all passed:
```
dagger run go run ./test -sdks python
```
> feat: add support to python 3.10

- flipt-client-browser/src/index.ts
- flipt-client-browser/src/models.ts
- flipt-engine-ffi/Cargo.toml
- flipt-engine-ffi/src/evaluator/mod.rs
- flipt-engine-ffi/src/parser/http.rs
- flipt-evaluation/src/parser/mod.rs
- flipt-evaluation/src/store/mod.rs
Fixes: #294 
Re: https://github.com/flipt-io/flipt/pull/3248
Supports `if-none-match/etag` headers in clients so we don't do the work of parsing/creating a new snapshot if no data has changed for this namespace
> feat: support etags in clients

- flipt-evaluation/src/lib.rs
Re: https://github.com/flipt-io/flipt/pull/3313
> fix: always return default reason/variant if nothing else

- ARCHITECTURE.md
- README.md
- flipt-client-go/README.md
> chore: update readmes to announce musl support

- flipt-client-go/evaluation.go
- flipt-client-go/evaluation_test.go
This is a breaking change on API level. 
As it's still v0 I think it's okay to make this change
> refactor(go)!: hide internals of ffi communication and provide cleaner client

- flipt-client-go/evaluation.go
- flipt-client-go/evaluation_test.go
- test/main.go
Trying to test invalid authentication errors from #347
> fix(go): return errors correctly from Go client

- .github/dependabot.yml
adds missing dependabot updates for:
- ruby
- dart
- java
> chore: add missing dependabot ecosystems

- .github/workflows/package-ffi-engine.yml
- Cargo.toml
- flipt-engine-ffi/Cargo.toml
- package/ffi/main.go
> Mobile build

- flipt-engine-ffi/Cargo.toml
`reqwest` uses `rust-native-tls` for tls. It requires openssl for linux but nothing for Windows or macOS. Per their suggestion for linux native-tls-vendored feature should be used to compile a copy of OpenSSL. This change reduces compilation time during the development on macOS
> chore(ffi): replace openssl with rust-native-tls crate

- .github/workflows/package-browser-sdk.yml
- .github/workflows/package-ffi-sdks.yml
- .github/workflows/test-sdks.yml
- package/ffi/main.go
- test/main.go
When I run `dagger run go run ./test --sdks=java` on main (on ARM machine) I get:
```
> Task :test FAILED
TestFliptEvaluationClient > initializationError FAILED
java.lang.UnsatisfiedLinkError at TestFliptEvaluationClient.java:25
```
When I run with this fix I get a successful test passing
> fix(java): loading lib on arm

- flipt-client-node/__tests__/evaluation.test.ts
- flipt-client-node/src/index.ts
- flipt-client-node/src/models.ts
- flipt-engine-wasm/src/lib.rs
- Adds list flags support to wasm engine
- Adds list flags back to node SDK
- Add list flags to browser SDK
> feat: add list flags to wasm/node SDK

- flipt-client-browser/README.md
- flipt-client-browser/__tests__/evaluation.test.js
- flipt-client-browser/package-lock.json
- flipt-client-browser/package.json
- flipt-client-browser/src/index.ts
- flipt-client-browser/src/models.ts
- flipt-client-browser/src/utils.ts
- flipt-client-node/src/index.ts
- test/main.go
- redoes browser client to use similar camel casing for field/argument names like in #373 
- adds list flags method to browser SDK
> refactor: browser argument casing + list flags

- flipt-client-browser/package-lock.json
- flipt-client-browser/package.json
- flipt-client-browser/src/index.ts
- flipt-client-browser/src/internal/models.ts
- flipt-client-browser/src/models.ts
- flipt-client-node/package-lock.json
- flipt-client-node/package.json
- flipt-client-node/src/index.ts
- flipt-client-node/src/internal/models.ts
- flipt-client-node/src/models.ts
I was working on a react wrapper SDK and realized that we don't export any of our models outside the main module.
This change re-exports those types so they can be used externally
> fix(node/browser): export models outside package

- .github/workflows/package-java-sdk.yml
- flipt-client-java/build.musl.gradle
- flipt-engine-ffi/Cargo.toml
- flipt-engine-wasm/Cargo.toml
- flipt-engine-wasm/LICENSE
- flipt-evaluation/Cargo.toml
- flipt-evaluation/LICENSE
- package/ffi/main.go
Re: https://github.com/flipt-io/flipt-client-sdks/issues/141#issuecomment-2391111354
> feat: build java musl lib

- flipt-client-browser/package.json
- flipt-client-browser/src/index.ts
It turns out that fetch API will got the HTTP 200 in browser even when server response will be HTTP 304.
https://stackoverflow.com/questions/62378379/do-the-fetch-api-and-axios-see-304-responses-as-200
> fix(browser): use another way for etag checking

- flipt-client-ruby/Gemfile
- flipt-client-ruby/Gemfile.lock
The older version depends on rexml which has few issues.
> chore(deps-dev): bump rubocop to 1.68 in flipt-client-ruby

- package/ffi/main.go
Should fix what I was seeing in https://github.com/flipt-io/flipt-client-sdks/pull/559#issuecomment-2523843142
The problem was that there was no libc set for Go (nor Java), so this line:
https://github.com/flipt-io/flipt-client-sdks/blob/ab2e0d52574c46c67b96f4a99a43129dcabedc3c/package/ffi/sdks/go.go#L66
Would evaluate as:
```
WithDirectory("/tmp/ext", hostDirectory.Directory("tmp/))
```
> build: go and java packaging now default to glibc

- flipt-client-java/build.gradle
- flipt-client-java/build.musl.gradle
- flipt-client-node/package-lock.json
- flipt-client-node/package.json
- release/sdks/base.py
This pull request includes several changes to update version numbers and refactor the version tagging process for the Flipt Client SDK. The most important changes include updating version numbers in multiple files and refactoring the `tag_and_push` method to improve code reuse.
Version updates:
* [`flipt-client-java/build.gradle`](diffhunk://#diff-4a63bec44c06a86119a7a73356fa8d771036df71984e1b85e5528bc36117242dL11-R11): Updated version from `0.11.0` to `0.12.0`.
* [`flipt-client-java/build.musl.gradle`](diffhunk://#diff-475ec335453b154e069b604264c36943f7889cb81733b56d8ae4401127b97353L11-R11): Updated version from `0.3.0` to `0.4.0`.
* [`flipt-client-node/package-lock.json`](diffhunk://#diff-c43eae3968c5c10eec23858caeaba1740e0210cf2b8418e8195dd70eb1ff9aedL3-R9): Updated version from …
> chore: forgot to update versions after release

- flipt-client-ruby/lib/flipt_client/version.rb
Release flipt-client-ruby-v0.13.0
> Release flipt-client-ruby-v0.13.0

- flipt-client-ruby/Gemfile.lock
- flipt-client-ruby/README.md
- flipt-client-ruby/Rakefile
- flipt-client-ruby/lib/flipt_client.rb
- flipt-client-ruby/spec/evaluation_spec.rb
This pull request updates error handling in the flipt-client-ruby. Previously, the gem raised a generic StandardError when API requests failed. With this change, the gem now raises a more specific Flipt::Error to improve error context and consistency.
Thanks!
> Raise Flipt::Error when Flipt API request failed

- flipt-client-java/build.musl.gradle
Reverts flipt-io/flipt-client-sdks#600
doesnt work
```
flipt-client-sdks/flipt-client-java - [main] » ./gradlew build --build-file build.musl.gradle
FAILURE: Build failed with an exception.
* Where:
Script '/Users/markphelps/workspace/flipt-client-sdks/flipt-client-java/build.gradle' line: 3
* What went wrong:
Could not compile script '/Users/markphelps/workspace/flipt-client-sdks/flipt-client-java/build.gradle'.
> startup failed:
script '/Users/markphelps/workspace/flipt-client-sdks/flipt-client-java/build.gradle': 3: Only Project and Settings build scripts can contain plugins {} blocks
For more information on the plugins {} block, please refer to https://docs.gradle.org/8.5/userguide/plugins.html#sec:plugins_block in the Gradle documentation.
@ line 3, column 1.
plugins {
^
1 error
```
> Revert "build(java): try to inherit build config/deps from main build.gradle"

- test/main.go
@markphelps Here are my changes to go into your branch if you are okay with them.
> fix: Use dagger to detect the arch and platform in stead of go runtime

- .github/workflows/package-ffi-sdks.yml
- .github/workflows/package-wasm-sdks.yml
- .github/workflows/test-sdks.yml
- CONTRIBUTING.md
- RELEASE.md
- release/README.md
- test/README.md
- test/main.go
Try to fix: #650 
@atmask mind giving this PR a try to see if it fixes the issue? I wonder if it has something to do with Rosetta like you mentioned. Hopefully specifying the platform for the rust image / lib compilation step fixes it
This pull request includes multiple changes across different files to update the Dagger version, enhance documentation, and improve the test setup. The most important changes are summarized below:
* Updated `DAGGER_VERSION` to `0.14.0` in `.github/workflows/package-ffi-sdks.yml` [[1]](diffhunk://#diff-109442fada4c603b457d3f8bb0aaefccf0638b63f00034797ed638296b59eb43L33-R33) `.github/workflows/package-wasm-sdks.yml` [[2]](diffhunk://#diff-13097cada9ececf2999d0023083271317c506d44a1a9fd5167498674f7b21227L16-R16) and `.github/workflows/test-sdks.yml` …
> chore: try to fix issue with dagger and host platform

- flipt-client-java/build.gradle
- flipt-client-java/build.musl.gradle
- flipt-client-java/gradle/libs.versions.toml
try to use [gradle catalogs](https://docs.gradle.org/current/userguide/version_catalogs.html) to share dependency versions (for dependabot updates) between the glibc and musl version of the Java SDK
> chore: try to share dependency versions for java sdk

- .github/dependabot.yml
- .github/workflows/test-android-sdk.yml
- flipt-client-kotlin-android/build.gradle
try to fix this warning:
```
C/C++: CMake Warning at /usr/local/lib/android/sdk/ndk/25.1.8937393/build/cmake/android-legacy.toolchain.cmake:415 (message):
C/C++:   An old version of CMake is being used that cannot automatically detect
C/C++:   compiler attributes.  Compiler identification is being bypassed.  Some
C/C++:   values may be wrong or missing.  Update to CMake 3.19 or newer to use
C/C++:   CMake's built-in compiler identification.
C/C++: Call Stack (most recent call first):
C/C++:   /usr/local/lib/android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake:54 (include)
C/C++:   /home/runner/work/flipt-client-sdks/flipt-client-sdks/flipt-client-kotlin-android/.cxx/Debug/2m5n4r4i/x86_64/CMakeFiles/3.18.1-g262b901/CMakeSystem.cmake:6 (include)
C/C++: …
```
> chore: specify Cmake version

- .github/workflows/package-ffi-engine.yml
- package/ffi/sdks/go.go
- package/ffi/sdks/swift.go
Re: #670 
- Adds missing macos targets for swift packaging
- Uses GitHub API to create a release after tagging for Swift and Go SDKs as they require separate repos
> chore: try to fix swift SDK release

- flipt-client-csharp/README.md
- flipt-client-csharp/src/FliptClient/Models/ClientOptions.cs
- flipt-client-go/README.md
- flipt-client-go/evaluation.go
- flipt-client-go/models.go
- flipt-engine-ffi/examples/evaluation.rs
- flipt-engine-ffi/src/http.rs
- flipt-engine-ffi/src/lib.rs
Renames `report` to `fail` for 'fail-fast' as I think report might be a bit confusing as we don't actually 'report' the error as in like report to Sentry or anything. I'm open to other names though
Also add a section in the C# readme explaining this new option. I'd like to release the C# client and then add this new option to the other SDKs as well
> feat: rename report error strategy to fail

- .github/workflows/package-go-sdk.yml
- .github/workflows/package-java-sdk.yml
- .github/workflows/package-wasm-sdks.yml
- .github/workflows/test-android-sdk.yml
- .github/workflows/test-engines.yml
- .github/workflows/test-sdks.yml
- .github/workflows/test-swift-sdk.yml
- package/ffi/main.go
- package/ffi/sdks/go.go
- package/ffi/sdks/swift.go
- package/wasm/main.go
- package/wasm/sdks/browser.go
- package/wasm/sdks/go.go
- package/wasm/sdks/node.go
- package/wasm/sdks/sdk.go
- test/main.go
Redoes the packaging code to work with the changes in #747 
I tested this by adding output to stdout using the `tree` command and ensured that all the contents for each SDK are in the correct places
> chore: Packaging for 'static' libs and Go (wasm)

- flipt-client-go/evaluation.go
fixes several issues found while teseting in 'real code':
1. `snapshotChan` fix double close, prevents: `panic: close of closed channel`
2. we were returning memory that was allocated by wasm and not Go at the end of the `evaluateWASM` call. this memory would get deallocated by wasm upon returning which would lead to corrupted memory when trying to perform the evaluate calls
3. `reader.ReadBytes` is blocking and was waiting on a streaming result so it would not return even if we were shutting down. this change makes it non-blocking/context aware
> fix(Go): fix memory corruption and blocking on close

- flipt-engine-wasm-js/Cargo.toml
- flipt-engine-wasm/Cargo.toml
- flipt-evaluation/Cargo.toml
- flipt-evaluation/src/store.rs
we dont really need uuids, we just need a string that is unique per flag/rule
this removes the uuid crate which doesn't really work on 'wasm32-unknown-unknown` anyways.. not that it really matters since we are building to `wasip1`.. but its always nice to remove dependencies
> chore: rm uuid dependency

- flipt-client-go/evaluation.go
- flipt-client-go/evaluation_test.go
- flipt-client-go/models.go
Fixes: #755 
- Adds retries for fetch and initiating streaming (currently 3x) with jitter
- Changes to build the URLs in the constructor, instead of each fetch call
> feat: Go retries

- .github/workflows/test-android-sdk.yml
- flipt-client-csharp/README.md
- flipt-client-dart/README.md
- flipt-client-go/README.md
- flipt-client-go/evaluation.go
- flipt-client-java/README.md
- flipt-client-kotlin-android/README.md
- flipt-client-python/README.md
- flipt-client-ruby/README.md
- flipt-client-swift/README.md
- flipt-engine-ffi/src/http.rs
This makes the retry functionality more consistent between Go and the FFI SDKs by:
1. Making min retry delay 1s
2. Making max retry delay 30s
3. Make exponential backoff consistent (2s, 4s, 8s) (note we never get to 30s with only 3 retries)
4. Adding Jitter to the rust impl
5. Handling certain transient HTTP statuses in the Go impl
Also adds retry info to the readmes of clients that implement it
---
This pull request includes several changes to improve the retry mechanism across multiple SDKs and the Go client. The most important changes include adding retry documentation to various SDK README files, modifying the retry logic in the Go client, and updating the HTTP retry policy in the Rust FFI.
Documentation updates:
* [`flipt-client-csharp/README.md`](diffhunk://#diff-a59842282a5e722b46ab …
> feat: make retries more consistent across Go and FFI impl

- .github/workflows/lint-sdks.yml
- flipt-client-browser/package-lock.json
- flipt-client-browser/package.json
- flipt-client-csharp/src/FliptClient/EvaluationClient.cs
- flipt-client-csharp/src/FliptClient/FliptClient.csproj
- flipt-client-csharp/src/FliptClient/Models/ClientOptions.cs
- flipt-client-csharp/src/FliptClient/Models/Request.cs
- flipt-client-csharp/src/FliptClient/Models/Response.cs
- flipt-client-csharp/src/FliptClient/NativeMethods.cs
- flipt-client-csharp/src/FliptClient/StyleCop.ruleset
- flipt-client-csharp/src/FliptClient/stylecop.json
- flipt-client-csharp/tests/FliptClient.Tests/EvaluationClientTests.cs
- flipt-client-go/evaluation.go
- flipt-client-kotlin-android/build.gradle
- flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
- flipt-client-kotlin-android/src/main/java/io/flipt/client/models/FetchMode.kt
- flipt-client-swift/.swiftformat
- flipt-client-swift/.swiftlint.yml
- flipt-client-swift/Sources/FliptClient/FliptClient.swift
- flipt-client-swift/Tests/FliptClientTests/FliptClientTests.swift
Add more linters for:
- Go
- Kotlin
- C#
- Swift
And fixing linter issues
Note: there are potential breaking changes in the C# SDK, mainly changing some fields to required/nullable as well as some arrays into Lists.. however as we are pre-1.0 there I think it is acceptable in the pursuit of more idiomatic code.
> chore: More linters

- flipt-client-java/build.gradle
- flipt-client-kotlin-android/build.gradle
- package/ffi/sdks/android.go
- package/ffi/sdks/java.go
this _should_ make it so when we publish the java and android SDKs that I no longer have to login to Sonatype and manually close and release the packages (as I sometimes forget)
> chore: use nexus publish plugin to autorelease java/android

- .github/workflows/lint-sdks.yml
- flipt-client-go/evaluation.go
- flipt-client-go/version.go
- release/sdks/go.py
there were a couple issues with the Go SDK, particularly when used with streaming mode
1. we set the wrong URL for the initial fetch
2. we weren't handling buffered responses like we can get from cloudflare
3. we weren't shutting down correctly, causing the waitgroup in Close to always block
Also made a few improvements:
1. set the user agent header (TODO: automate incrementing of version number in `version.go` on release)
2. don't check engine initialization on each method call, only in `NewEvaluationClient`
> fix(go): client streaming url

- flipt-engine-wasm-js/Cargo.toml
re: https://github.com/rustwasm/wasm-bindgen/issues/4122
it also seems that dependabot is not working with our cargo dependencies :(
looking at [dependabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-) it seems they only support cargo v1, whereas we are using v2
also could be an issue with us using cargo workspaces.. but we are defining the version dependencies in the child crates so idk
> chore: bump wasm-bindgen to remove console log warning

- flipt-client-python/flipt_client/models.py
- flipt-client-python/tests/__init__.py
- flipt-client-ruby/spec/client_spec.rb
- test/fixtures/testdata/features.yml
This update introduces a `FlagType` enum to represent the `type` field of the `Flag` class in the Python SDK. It enhances clarity and allows easier validation of key types returned by the `list_flags` API.
> chore: FlagType enum for Python SDK

- .github/workflows/package-ffi-engine-ios.yml
This pull request introduces a new GitHub Actions workflow to automate the packaging of the FFI engine for iOS. The workflow includes steps to fetch release assets, process them into an `xcframework`, and upload the resulting framework as a release asset.
* **Workflow Name and Trigger**:
- Added a new workflow named "Package FFI Engine (iOS)" that can be triggered manually via `workflow_dispatch`. It requires a `tag` input to specify the release. (`.github/workflows/package-ffi-engine-ios.yml`)
* **Token Generation**:
- Integrated the `tibdex/github-app-token` action to generate a GitHub App token using secrets for authentication. (`.github/workflows/package-ffi-engine-ios.yml`)
* **Release Asset Handling**:
- Added steps to fetch URLs for specific release assets …
> chore: package ios engine for use in dart

- flipt-client-js/src/browser/index.ts
- flipt-client-js/src/node/index.ts
- flipt-client-js/src/slim/index.ts
- flipt-client-js/tsconfig.json
Fixes: #964
Remove path aliases which generate type files with improper imports once built
This now generates relative imports like:
```
import { BaseFliptClient } from '../core/base';
import { ClientOptions } from '../core/types';
export * from '../core/types';
export * from '../core/base';
```
> fix(js): rm path alias

- .github/workflows/package-ffi-engine-darwin.yml
- package/ffi/sdks/dart.go
- strip_xcframework.sh
This is to get around this error on dart publish: https://github.com/flipt-io/flipt-client-sdks/actions/runs/14742115179/job/41382300626#step:7:3573
This removed like 12MB from the uncompressed package which should hopefully let us get under the 100MB limit
This strips the .a files for iOS before adding them to the dart library. I put some TODOs in there as this is a temporary fix as we should:
1. strip them in the package-ios action before adding to the release
2. see if we can produce smaller .a files from the rust lib builds
> chore: strip the ios .a libs before dart publish

- .github/workflows/package-ffi-engine-android.yml
- .github/workflows/package-ffi-engine-darwin.yml
- .github/workflows/package-ffi-engine-linux.yml
- .github/workflows/package-ffi-engine-windows.yml
- Cargo.toml
- flipt-engine-ffi/build.sh
experiment to build smaller libs for FFI
https://github.com/johnthagen/min-sized-rust?tab=readme-ov-file#remove-location-details
https://github.com/johnthagen/min-sized-rust?tab=readme-ov-file#remove-fmtdebug
seems to remove about 4-6mb per library which is nice
> chore: try to build smaller libs

- flipt-client-react/README.md
- flipt-client-react/package-lock.json
- flipt-client-react/package.json
- flipt-client-react/src/useFliptClient.ts
Adding this shim allows the Flipt react SDK to be used in react 17.
Shim package [here](https://www.npmjs.com/package/use-sync-external-store).
It only uses the shim if the hook is not present in the version of react that you're using.
> Use shim for useSyncExternalStore

- flipt-client-dart/README.md
- flipt-client-dart/lib/src/ffi/loader.dart
- flipt-client-dart/pubspec.yaml
- package/ffi/sdks/dart.go
remove support for mac0S x86 for Dart as we keep running into package size issues on publish:
https://github.com/flipt-io/flipt-client-sdks/actions/runs/15537275378/job/43739269588#step:7:3075
ie: `Message from server: Uncompressed package archive is too large (size > 104857600).`
> chore!(dart): rm macos x86 support to decrease file size

- flipt-client-react/README.md
- flipt-client-react/package-lock.json
- flipt-client-react/package.json
- flipt-client-react/src/provider.test.tsx
- flipt-client-react/src/provider.tsx
- flipt-client-react/src/useFliptClient.ts
Closes: #1059 
- adds ability to set env for react client
- moves namespace/env to options
> feat!(react): add env support and move namespace to options

- flipt-client-java/README.md
- flipt-client-java/src/main/java/io/flipt/client/FliptClient.java
- flipt-client-java/src/main/java/io/flipt/client/models/ClientOptions.java
- flipt-client-java/src/main/java/io/flipt/client/models/TlsConfig.java
- flipt-client-java/src/test/java/TestFliptClient.java
- flipt-client-python/flipt_client/models.py
- flipt-engine-ffi/src/http.rs
- flipt-engine-ffi/src/lib.rs
- test/main.go
- Add comprehensive TLS configuration options to the Java client SDK, matching the functionality from the Python implementation
- Add TlsConfig class with builder pattern and static factory methods
- Support CA certificates (file paths and raw data), client certificates for mutual TLS, and insecure mode for development
- Update ClientOptions and FliptClient to accept TLS configuration
- Update tests to handle HTTPS URLs with TLS configuration automatically
- Add comprehensive README documentation with examples
cc @cristianonicolai
> feat: add TLS configuration support to Java SDK

- flipt-engine-ffi/Cargo.toml
- flipt-engine-ffi/src/http.rs
- flipt-engine-ffi/src/lib.rs
adds a bit more logging for each request, not just after all retries are exhausted
**Update**: This also 'forces' rustls usage by reqwest which i didnt realize wasnt guaranteed : https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.use_rustls_tls
Perhaps this will fix the underlying TLS issues we are seeing in https://github.com/orgs/flipt-io/discussions/4366
Theres quite a bit of traction to use rustls by default in reqwest fwiw: https://github.com/seanmonstar/reqwest/issues/2025
```
70  : [46.9s] | [2025-07-02T20:45:28Z DEBUG fliptengine::http] request GET http://invalid.flipt.com/internal/v1/evaluation/snapshot/namespace/default
70  : [46.9s] | [2025-07-02T20:45:28Z DEBUG reqwest::connect] starting new connection:
70  : [46.9s] | [2025-07-02T20:45:28Z WARN …
```
> feat: more debug logging for http failures

- flipt-engine-ffi/Cargo.toml
- flipt-engine-ffi/src/http.rs
Fixes TLS self-signed certificate validation issue in the Rust FFI engine where custom CA certificates failed to validate properly.
Users reported that self-signed certificates were not working properly with the Flipt client SDKs, with only `TlsConfig.insecure()` bypassing the issue. The error "remote error: tls: unknown certificate" indicated certificate validation problems.
The root cause was in the `configure_tls()` function which used `add_root_certificate()` to add custom CA certificates to the existing system certificate store. This approach doesn't work for self-signed certificates because:
1. Self-signed certificates need to be the only trusted CA for that connection
2. System default certificate validation was still being applied
3. Hostname verification could fail with …
> fix(engine-ffi): resolve TLS self-signed certificate validation by using custom root store

- flipt-client-kotlin-android/build.gradle
- package/ffi/sdks/android.go
Updates the Kotlin Android SDK to use the new Sonatype Central Portal configuration, bringing it in line with the Java SDK changes from commits c8fe178 and 83a3504.
- ✅ Upgraded nexus plugin from version 1.3.0 to 2.0.0
- ✅ Updated Sonatype URLs:
- From: `https://s01.oss.sonatype.org/service/local/`
- To: `https://ossrh-staging-api.central.sonatype.com/service/local/`
- ✅ Updated snapshot repository URL:
- From: `https://s01.oss.sonatype.org/content/repositories/snapshots/`
- To: `https://central.sonatype.com/repository/maven-snapshots/`
- ✅ Updated environment variables:
- From: `MAVEN_USERNAME` / `MAVEN_PASSWORD`
- To: `SONATYPE_PORTAL_USERNAME` / `SONATYPE_PORTAL_PASSWORD`
- ✅ Removed old maven repository configuration (now handled by nexus plugin)
- ✅ Updated environment variable …
> chore: update kotlin android sdk to use new sonatype portal

- flipt-client-ruby/Gemfile.lock
- flipt-client-ruby/README.md
- flipt-client-ruby/lib/flipt_client/models.rb
- flipt-client-ruby/spec/client_spec.rb
Adds `insecure_skip_hostname_verify` support to the Ruby SDK `TlsConfig` class for handling self-signed certificates with hostname mismatches.
- Add `insecure_skip_hostname_verify` field to `TlsConfig` class
- Update Ruby documentation with usage examples
- Add comprehensive RSpec tests for hash serialization
- Follow Ruby naming conventions (snake_case)
- **Model Update**: Added `insecure_skip_hostname_verify` parameter to `TlsConfig` class initialization
- **Serialization**: Updated `to_h` method to include the new field when set (excludes when nil)
- **Documentation**: 
- Updated README with field description and usage example for self-signed certificates
- Added proper YARD documentation for the parameter
- **Tests**: Added three RSpec tests to verify hash serialization works …
> feat(ruby): add insecure_skip_hostname_verify support to TlsConfig

- package/ffi/sdks/swift.go
Re: #1227 
Fixes the Swift SDK SPM installation failure by adding missing XCFramework components that are required for Swift Package Manager to properly recognize and import the framework.
Users reported that the Swift SDK cannot be installed via SPM, encountering errors when trying to add the package through Xcode or command line. This is a regression from previous working versions.
The XCFramework generated by the Swift build process was missing two critical components:
1. **Info.plist** - Root-level descriptor file that tells SPM about available platforms and architectures
2. **module.modulemap** - Files that allow Swift to import C headers as modules
Updated the Swift build script (`package/ffi/sdks/swift.go`) to generate:
- Root `Info.plist` with proper platform descriptors for iOS …
> fix(swift): add missing Info.plist and module.modulemap to XCFramework

- CLAUDE.md
- flipt-client-swift/README.md
- flipt-client-swift/Sources/FliptClient/FliptClient.swift
- flipt-client-swift/Sources/FliptClient/TlsConfig.swift
- flipt-client-swift/Tests/FliptClientTests/FliptClientTests.swift
Implements complete TLS configuration support for the Swift SDK, including the critical `insecureSkipHostnameVerify` option needed for self-signed certificates with hostname mismatches.
- **New TlsConfig struct** with builder pattern for fluent configuration
- **All TLS configuration options** including CA certs, client certs for mTLS, and insecure modes
- **insecureSkipHostnameVerify field** specifically addresses issue requirements
- **File validation** in builder with proper error handling
- **JSON serialization** with snake_case conversion for FFI engine compatibility
- **FliptClient integration** with new tlsConfig parameter
- **Test environment support** matching Java SDK pattern with FLIPT_CA_CERT_PATH
- **Comprehensive unit tests** for serialization behavior
- **Complete …
> feat(swift): add TlsConfig support with insecureSkipHostnameVerify

- flipt-client-js/src/browser/index.ts
- flipt-client-js/src/core/base.ts
- flipt-client-js/src/core/types.ts
- flipt-client-js/src/node/index.ts
- flipt-client-js/src/slim/index.ts
This pull request introduces a new "hook" mechanism to the Flipt client, enabling users to inject custom logic before and after flag evaluations. The changes add a `Hook` interface, update the client options to accept hooks, and ensure that hook callbacks are invoked at the appropriate points in the evaluation lifecycle for both boolean and variant flag evaluations, including batch operations. Additionally, the evaluation response types are updated to include segment information.
**API enhancements:**
* Extended `BooleanEvaluationResponse` to include a `segmentKeys` property, providing additional context about which segments impacted the evaluation.
> feat(js): introduce evaluation hook
