flipt-io/flipt-client-sdks

build/main.go
flipt-client-node/package.json

chore: setup build/push workflow for node

---

Makefile
build/main.go
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/flipt-client-ruby.gemspec

chore: Push python

---

flipt-engine/src/parser/mod.rs

fix: return error on http status >= 400

---

flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

These will have the new engine fixes in (#100) once tagged and pushed

chore: prep for v0.0.4 release of clients

---

.dockerignore
flipt-client-go/evaluation.go
flipt-client-go/models.go
flipt-client-node/src/index.ts
flipt-client-node/src/models.ts
flipt-client-python/flipt_client/__init__.py
flipt-client-python/flipt_client/models.py
flipt-client-python/scripts.py
flipt-client-python/tests/__init__.py
flipt-client-ruby/lib/flipt_client.rb
flipt-engine-ffi/examples/evaluation.rs
flipt-engine-ffi/src/lib.rs
flipt-evaluation/src/parser/mod.rs

Fixes: FLI-745
- Adds ability to pass down `reference` to a specific Git (for now) ref when using git backend for evaluation
- Also fixes an issue where the Python tests weren't being reported as failure
- Also fixes the ability to run on x86 for linux 🙈

feat: Client refs

---

flipt-client-go/evaluation.go
flipt-client-go/evaluation_test.go
flipt-client-go/models.go
flipt-client-ruby/lib/flipt_client.rb
flipt-client-ruby/lib/flipt_client/models.rb
flipt-client-ruby/spec/evaluation_spec.rb
flipt-evaluation/src/parser/mod.rs

Add a couple auth helpers for Go/Ruby to make it easier to setup auth

feat: add authentication helpers for Ruby and Go

---

flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

chore: bumping versions for release

---

flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

We never released the clients after #128 was merged
This adds batch functionality to the client sdks

chore: prep for v0.2.0 release

---

Makefile
build/main.go
flipt-client-java/build.gradle
flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
test/main.go

Add shared library to resources directory, so it can be included in the jar archive.

chore(java): add dynamic library to resources directory

---

README.md
flipt-client-java/README.md

chore: add docs for java

---

README.md

chore: update readme to mention glibc requirement

---

Makefile
flipt-evaluation/src/lib.rs
flipt-evaluation/src/models/common.rs
flipt-evaluation/src/models/source.rs

Add entityId for constraint comparisons.

feat(evaluation): add entityId for constraint comparisons

---

flipt-evaluation/src/lib.rs

fix(evaluation): add isoneof isnotoneof operators to string evaluation

---

.github/workflows/test-engine.yml

chore: try to setup codecov

---

flipt-client-go/evaluation.go

fix(go): try to fix cgo linkage once more

---

flipt-client-go/README.md

Re: https://github.com/flipt-io/flipt-client-sdks/issues/187#issuecomment-2023346619

chore: update go readme around linking shenanigans

---

flipt-client-java/build.gradle
flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

Bringing in changes in engine, mostly from #204

chore: prep for release of latest client sdks for engine changes

---

flipt-evaluation/src/lib.rs

related flipt-io/flipt#2910 flipt-io/flipt#2918

fix(evaluation): Evaluation bug when mixing boolean and other constraints

---

.github/workflows/lint-sdks.yml
flipt-client-ruby/.rubocop.yml
flipt-client-ruby/.rubocop_todo.yml
flipt-client-ruby/Gemfile.lock
flipt-client-ruby/flipt-client-ruby.gemspec
flipt-client-ruby/lib/flipt_client.rb
flipt-client-ruby/lib/flipt_client/models.rb
flipt-client-ruby/loadtest.rb
flipt-client-ruby/spec/evaluation_spec.rb

- Adds Ruby lint step
- Fixes Rubocop errors

chore: Rubocop

---

build/wasm/main.go
flipt-client-browser/.gitignore
flipt-client-browser/__tests__/evaluation.test.js
flipt-client-browser/jest.config.js
flipt-client-browser/jest.setup.js
flipt-client-browser/package-lock.json
flipt-client-browser/package.json
flipt-client-browser/src/index.ts
flipt-client-browser/src/models.ts
flipt-client-browser/tsconfig.json
flipt-client-node/.gitignore
flipt-client-node/src/index.ts
flipt-engine-ffi/src/evaluator/mod.rs
flipt-engine-wasm/src/lib.rs
flipt-evaluation/src/lib.rs
test/main.go

feat: Batch eval wasm

---

flipt-client-browser/package-lock.json
flipt-client-browser/package.json

will add support for batch eval

chore: bump flipt-client-browser for release

---

.github/workflows/package-ffi-sdks.yml
flipt-client-java/build.gradle
flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

chore: bump client versions for release

---

flipt-client-node/package-lock.json
flipt-client-node/package.json

prep for release of flipt-client-node
fix tsc build

chore: Node ffi release

---

flipt-client-java/build.gradle
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

chore: prep other libs based on updated engine

---

flipt-evaluation/src/lib.rs

https://github.com/flipt-io/flipt-client-sdks/actions/runs/9067151090/job/24911610703

chore(evaluation): make clippy happy about clone

---

flipt-client-node/src/index.ts
flipt-client-node/src/models.ts

docs(node): improve ts documentation

---

flipt-client-node/src/index.ts
flipt-client-python/flipt_client/__init__.py
flipt-client-ruby/lib/flipt_client.rb
go.work.sum

I asked chatgpty to help make the dynamic lib loading more idiomatic in the source languages

chore: load libs more idiomatically in client langs

---

flipt-client-java/build.gradle
flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-python/pyproject.toml
flipt-client-ruby/lib/flipt_client/version.rb

chore: prep for releasing new client versions

---

flipt-client-browser/package-lock.json
flipt-client-browser/package.json
flipt-client-browser/src/index.ts
flipt-client-browser/src/models.ts
flipt-client-go/evaluation_test.go

flipt-client-browser: make opts optional

chore: cleanup flipt-client-browser opts

---

flipt-client-browser/README.md

Add docs for browser sdk around custom fetcher and etag support

docs(browser): Add documentation around custom fetcher and etag support

---

flipt-client-browser/README.md
flipt-client-dart/.gitignore
flipt-client-dart/CHANGELOG.md
flipt-client-dart/LICENSE
flipt-client-dart/README.md
flipt-client-dart/analysis_options.yaml
flipt-client-dart/build.yaml
flipt-client-dart/lib/flipt_client.dart
flipt-client-dart/lib/src/flipt_evaluation_client.dart
flipt-client-dart/lib/src/models.dart
flipt-client-dart/lib/src/models.g.dart
flipt-client-dart/pubspec.yaml
flipt-client-dart/test/flipt_client_test.dart
flipt-client-go/README.md
flipt-client-java/README.md
flipt-client-node/README.md
flipt-client-python/README.md
flipt-client-ruby/README.md
flipt-engine-ffi/src/http.rs
test/main.go

Re: #32
Adds `flipt-client-dart` SDK for dart language using FFI

feat: add dart client

---

.github/workflows/package-dart-sdk.yml
.github/workflows/package-ffi-sdks.yml
RELEASE.md
flipt-client-dart/.pubignore
flipt-client-dart/pubspec.yaml
package/ffi/main.go

https://pub.dev/packages/flipt_client
https://dart.dev/tools/pub/automated-publishing#publishing-packages-using-github-actions

chore: setup workflow to publish dart client

---

flipt-client-browser/package-lock.json
flipt-client-browser/package.json
flipt-client-browser/src/index.ts

fix(browser): fix reference query param

---

.github/workflows/package-ffi-engine.yml
flipt-client-browser/README.md
flipt-client-browser/__tests__/evaluation.test.js
flipt-client-browser/package-lock.json
flipt-client-browser/package.json
flipt-client-browser/src/index.ts
flipt-client-browser/src/models.ts

feat: rm result types from browser sdk

---

flipt-client-go/README.md
flipt-client-go/evaluation.go
flipt-client-go/evaluation_test.go

refactor!(go):  hide result types from go-sdk

---

.github/workflows/package-browser-sdk.yml
.github/workflows/package-go-sdk.yml
.github/workflows/package-java-sdk.yml
.github/workflows/package-node-sdk.yml
.github/workflows/package-python-sdk.yml
.github/workflows/package-ruby-sdk.yml
.github/workflows/package-wasm-sdks.yml
flipt-client-node/package-lock.json
flipt-client-node/package.json

fix publish workflow for node SDK

chore: fix publish workflow for node SDK

---

flipt-client-browser/src/index.ts
flipt-client-node/src/index.ts
flipt-engine-wasm/src/lib.rs

fix(wasm): prevent panic in the wasm

---

.github/workflows/test-engines.yml
flipt-engine-wasm/README.md
flipt-engine-wasm/src/lib.rs
flipt-evaluation/src/lib.rs
flipt-evaluation/src/models/source.rs

fix(wasm): add wasm tests

---

flipt-client-java/src/main/java/io/flipt/client/EvaluationException.java
flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
flipt-client-java/src/test/java/TestFliptEvaluationClient.java

refactor(java)!: hide result type from java sdk

---

flipt-client-browser/__tests__/evaluation.test.js
flipt-client-browser/src/index.ts

Sometime it would be helpful to understand if the any changes in the
snapshot after the refresh.

feat(browser): allow caller to know if the snapshot was updated

---

package/ffi/main.go

windows build should exist for both glibc and musl (as its not relevant)

chore: fix windows packaging workflow

---

flipt-client-dart/pubspec.yaml

chore: bump dart version; include windows dll

---

flipt-client-browser/README.md
flipt-client-node/README.md
flipt-client-node/package-lock.json
flipt-client-node/package.json
flipt-client-node/src/index.ts

feat: expose if refresh changed state in node sdk

---

flipt-client-react/README.md
flipt-client-react/eslint.config.mjs
flipt-client-react/package-lock.json
flipt-client-react/package.json
flipt-client-react/src/provider.tsx
flipt-client-react/src/useFliptClient.ts

Try to work around issue re NextJS app router: https://github.com/vercel/next.js/issues/55537

chore: Nextjs app router support

---

flipt-client-dart/README.md
flipt-client-dart/pubspec.yaml
flipt-client-go/README.md
flipt-client-java/README.md
flipt-client-java/build.gradle
flipt-client-java/build.musl.gradle
flipt-client-python/README.md
flipt-client-python/pyproject.toml
flipt-client-ruby/README.md
flipt-client-ruby/lib/flipt_client/version.rb
flipt-engine-wasm/README.md

- Add streaming options and descriptions
- Bump versions in prep for release

chore: Streaming readme updates

---

.release-please-manifest.json
flipt-engine-ffi/Cargo.toml

to get in sync with latest tag

chore: update engine version to match latest

---

README.md
flipt-client-swift/README.md
release/release.py
release/sdks/__init__.py
release/sdks/csharp.py
release/sdks/swift.py

- add swift readme
- update main readme
- add release scripts for swift and c#

chore: Swift readme

---

flipt-client-node/README.md

remove warning about nextjs in node readme

chore: Update README.md

---

flipt-client-browser/package-lock.json
flipt-client-browser/package.json
flipt-client-react/package-lock.json
flipt-client-react/package.json
release/release.py
release/sdks/base.py

Release flipt-client-browser-v0.4.0

Release flipt-client-browser-v0.4.0

---

flipt-client-python/pyproject.toml

Release flipt-client-python-v0.13.0

Release flipt-client-python-v0.13.0

---

flipt-client-csharp/src/FliptClient/FliptClient.csproj

Release flipt-client-csharp-v0.1.0

Release flipt-client-csharp-v0.1.0

---

.github/workflows/lint-sdks.yml
.github/workflows/package-dart-sdk.yml
.github/workflows/test-engines.yml
.github/workflows/test-sdks.yml
.github/workflows/test-swift-sdk.yml
flipt-client-ruby/lib/flipt_client/version.rb
release/sdks/base.py
release/sdks/ruby.py

chore: comment on releases with tags of sdks; dont run workflows on release branches

chore: comment on releases with tags of sdks; dont run workflows on release branches

---

flipt-engine-ffi/src/http.rs

Should fix: #593 
This changes the FFI http code to clear the etag on any error responses from the server. This means that on the next request it should re-request fresh state when successful, which will then clear the stored error from the previous request in the snapshot store

fix(ffi): clear stored etag on http req failure

---

flipt-client-python/pyproject.toml

Release flipt-client-python-v0.13.1

Release flipt-client-python-v0.13.1

---

flipt-client-ruby/lib/flipt_client/version.rb
release/sdks/base.py

Release flipt-client-ruby-v0.13.1

Release flipt-client-ruby-v0.13.1

---

.github/workflows/lint-sdks.yml
.github/workflows/test-engines.yml
.github/workflows/test-sdks.yml
.github/workflows/test-swift-sdk.yml
flipt-client-java/build.gradle
release/sdks/base.py

"Release flipt-client-java-v0.12.1"

"Release flipt-client-java-v0.12.1"

---

flipt-client-python/pyproject.toml

Release flipt-client-python-v0.14.0

Release flipt-client-python-v0.14.0

---

flipt-client-react/package-lock.json
flipt-client-react/package.json

Release flipt-client-react-v0.3.0

Release flipt-client-react-v0.3.0

---

flipt-client-csharp/src/FliptClient/Models/ClientOptions.cs
flipt-engine-ffi/examples/evaluation.rs
flipt-engine-ffi/src/http.rs
flipt-engine-ffi/src/lib.rs

feat(engine-ffi): add option to evaluate the flag against the stale cache

---

.github/workflows/package-ffi-engine.yml

Re: https://github.com/flipt-io/flipt-client-sdks/actions/runs/13158647864
See: https://github.com/cross-rs/cross/issues/1619#issuecomment-2636543283

chore: try to fix cross build

---

flipt-client-go/README.md
flipt-client-go/evaluation.go
flipt-client-go/models.go

feat(go): impl error strategy options

---

flipt-client-csharp/src/FliptClient/FliptClient.csproj

Release flipt-client-csharp-v0.2.0

Release flipt-client-csharp-v0.2.0

---

flipt-client-swift/Sources/FliptEngineFFI.xcframework/macos-x86_64/Headers/module.modulemap

Re: https://github.com/flipt-io/flipt-client-sdks/actions/runs/13203552309/job/36861187170

chore: Fix swift release

---

flipt-client-swift/README.md
flipt-client-swift/Sources/FliptClient/FliptClient.swift

- prep for 1.0.0 release of swift sdk
- implement error strategy support

feat: Swift error strategy

---

flipt-client-csharp/src/FliptClient/FliptClient.csproj

Release flipt-client-csharp-v0.3.0

Release flipt-client-csharp-v0.3.0

---

flipt-client-ruby/README.md
flipt-client-ruby/lib/flipt_client.rb

feat(ruby): added error strategy option

---

.github/workflows/test-engines.yml
.github/workflows/test-swift-sdk.yml
flipt-client-java/README.md
flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
flipt-client-java/src/main/java/io/flipt/client/models/ClientOptions.java
flipt-client-java/src/main/java/io/flipt/client/models/ErrorStrategy.java

feat(java): added error strategy option

---

flipt-client-python/README.md
flipt-client-python/flipt_client/models.py
flipt-client-ruby/README.md

feat(python): added error strategy option

---

.github/workflows/package-ffi-engine-linux.yml
.github/workflows/test-android-sdk.yml
flipt-client-kotlin-android/README.md
flipt-client-kotlin-android/build.gradle
flipt-client-kotlin-android/gradle/wrapper/gradle-wrapper.properties
flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ErrorStrategy.kt
flipt-client-kotlin-android/src/test/java/io/flipt/client/TestOptionsEncoding.kt

feat(android): added error strategy option

---

.github/workflows/package-ffi-engine-android.yml
.github/workflows/package-ffi-engine-darwin.yml
.github/workflows/package-ffi-engine-linux.yml
.github/workflows/test-android-sdk.yml
.github/workflows/test-sdks.yml
.github/workflows/test-swift-sdk.yml
README.md
flipt-client-java/README.md
flipt-engine-ffi/build.sh
package/ffi/main.go
package/ffi/platform/platform.go
package/ffi/sdks/csharp.go
package/ffi/sdks/dart.go
package/ffi/sdks/java.go
package/ffi/sdks/python.go
package/ffi/sdks/ruby.go
package/ffi/sdks/sdk.go
package/ffi/sdks/swift.go
test/main.go

This PR will build the static lib into a .so before release for linux
We need to merge this first before creating a new engine release, then I can test the packaging of the SDKs

chore: package musl

---

flipt-client-java/build.gradle

Release flipt-client-java-v0.15.0

Release flipt-client-java-v0.15.0

---

.github/workflows/lint-sdks.yml
.github/workflows/package-ffi-engine-android.yml
.github/workflows/package-ffi-engine-darwin.yml
.github/workflows/package-ffi-engine-linux.yml
.github/workflows/package-ffi-engine-windows.yml
.github/workflows/test-engines.yml
.github/workflows/test-sdks.yml

This pull request includes several changes to GitHub workflow files to update the triggering conditions for various workflows. The most important changes include modifying the `pull_request` triggers to include specific paths for the FFI Engine packaging workflows and removing the `push` triggers for the main branch in several workflows.
* [`.github/workflows/package-ffi-engine-android.yml`](diffhunk://#diff-a044f7d2ebf8014bdaa1c8969d8a91c4598785c2f0848b4adc41aceaded2ab9aR5-R7): Added specific paths to the `pull_request` trigger to include changes in `flipt-engine-ffi` and `flipt-evaluation`.
* [`.github/workflows/package-ffi-engine-darwin.yml`](diffhunk://#diff-c9b2f50cd118283630ad033f3253e12ebd9f4cfff21121b1a0f251fe7a13efc6R5-R7): Added specific paths to the `pull_request` trigger to …

chore: reduce times we run some actions workflows

---

flipt-engine-wasm/src/lib.rs

remove more `unwrap` calls and handle potential panics better in flipt-engine-wasm

chore: better handle potential panics in wasm engine

---

.github/workflows/package-wasm-engine.yml
.github/workflows/package-wasm-js-engine.yml

First part of #756
Build and upload packaged wasm on release

chore: package wasm code for releases

---

.github/workflows/package-android-sdk.yml
flipt-client-kotlin-android/build.gradle
package/ffi/main.go
package/ffi/platform/platform.go
package/ffi/sdks/android.go
package/ffi/sdks/csharp.go
package/ffi/sdks/dart.go
package/ffi/sdks/java.go
package/ffi/sdks/python.go
package/ffi/sdks/ruby.go
package/ffi/sdks/sdk.go
package/ffi/sdks/swift.go
package/wasm/main.go
package/wasm/sdks/browser.go
package/wasm/sdks/go.go
package/wasm/sdks/node.go
package/wasm/sdks/sdk.go
release/release.py
release/sdks/__init__.py
release/sdks/android.py

chore: Package android

---

flipt-client-go/evaluation.go
flipt-client-go/evaluation_test.go
flipt-client-go/models.go

- remove applications
- close channel when streaming is done
- close fully read the http body for streaming
- infinitive retry for streaming
- remove unused struct

refactor(go): tweak a go client

---

flipt-client-csharp/README.md
flipt-client-csharp/src/FliptClient/Models/ClientOptions.cs
flipt-client-csharp/tests/FliptClient.Tests/EvaluationClientTests.cs
flipt-client-dart/README.md
flipt-client-dart/lib/src/models.dart
flipt-client-dart/lib/src/models.g.dart
flipt-client-java/README.md
flipt-client-java/src/main/java/io/flipt/client/FliptEvaluationClient.java
flipt-client-java/src/main/java/io/flipt/client/models/ClientOptions.java
flipt-client-kotlin-android/README.md
flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
flipt-client-python/README.md
flipt-client-python/flipt_client/models.py
flipt-client-ruby/README.md
flipt-client-ruby/lib/flipt_client.rb
flipt-client-swift/README.md
flipt-client-swift/Sources/FliptClient/FliptClient.swift

Closes: #738 
Adds requestTimeout support options to:

Add request timeout

---

.github/workflows/lint-sdks.yml
flipt-client-kotlin-android/src/main/java/io/flipt/client/CLibrary.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/EvaluationException.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/AuthenticationStrategy.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/BatchEvaluationResponse.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/BooleanEvaluationResponse.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ErrorEvaluationResponse.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ErrorStrategy.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/EvaluationRequest.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/FetchMode.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/Flag.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/Response.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/Result.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/VariantEvaluationResponse.kt

actually format the kotlin code

chore: Fix kotlin fmt

---

flipt-client-go/README.md

added missing context for client.Close

docs(go): update the readme example with new api

---

flipt-client-js/package-lock.json
flipt-client-js/package.json
flipt-client-js/rollup.config.js
flipt-client-js/src/core/base.ts
flipt-client-js/src/index.ts
flipt-client-react/package-lock.json
flipt-client-react/package.json
flipt-client-react/rollup.config.mjs
flipt-client-react/src/provider.test.tsx
flipt-client-react/src/provider.tsx
flipt-client-react/src/useFliptClient.ts
flipt-client-react/tsconfig.json

updates react sdk to use js sdk

chore: use new js client in react sdk

---

flipt-client-react/README.md
flipt-client-react/package-lock.json
flipt-client-react/package.json
flipt-client-react/src/useFliptClient.ts

- fixes an issue where updateInterval was not converted to seconds if passed in to react client
- makes client compatible with react 18 - 19

fix(react): convert updateInterval to seconds; support react 18-19

---

flipt-client-js/src/node/index.ts
flipt-evaluation/src/lib.rs

add test for cases like in https://github.com/flipt-io/flipt/pull/4018

chore: add unknown operator test

---

flipt-client-dart/README.md
flipt-client-dart/lib/src/flipt_evaluation_client.dart
flipt-client-dart/pubspec.yaml
flipt-client-go/version.go
package/ffi/sdks/dart.go

Re: #945 
this may be all we need to do to get dart working on mobile 🤔

feat: Dart mobile

---

.gitignore
flipt-client-dart/.gitignore
flipt-client-dart/flutter_plugin.yaml
flipt-client-dart/pubspec.yaml

chore: try to fix flutter lib bundling

---

flipt-client-java/README.md
flipt-client-kotlin-android/.editorconfig
flipt-client-kotlin-android/README.md
flipt-client-kotlin-android/src/androidTest/java/io/flipt/client/TestFliptEvaluationClient.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/CLibrary.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/FliptEvaluationClient.kt
flipt-client-kotlin-android/src/main/java/io/flipt/client/models/ClientOptions.kt
flipt-client-kotlin-android/src/test/resources/empty_snapshot.json
flipt-client-kotlin-android/src/test/resources/snapshot.json

add get/setSnapshot support for android sdk

feat(kotlin): add snapshot support

---

flipt-client-ruby/.rubocop.yml
flipt-client-ruby/.rubocop_todo.yml
flipt-client-ruby/Gemfile.lock
flipt-client-ruby/README.md
flipt-client-ruby/flipt-client-ruby.gemspec
flipt-client-ruby/lib/flipt_client.rb
flipt-client-ruby/lib/flipt_client/models.rb
flipt-client-ruby/loadtest.rb
flipt-client-ruby/spec/client_spec.rb

feat!(ruby): refactor for 1.0

---

flipt-client-js/src/browser/index.ts
flipt-client-js/src/core/types.ts
flipt-client-js/src/node/index.ts
flipt-client-js/src/slim/index.ts

feat(js): add flipt v2 env support

---

flipt-client-kotlin-android/gradle/wrapper/gradle-wrapper.properties
flipt-engine-ffi/src/http.rs
flipt-engine-ffi/src/lib.rs

- adds more logging around tls config and http operations
- fixes `FLIPT_ENGINE_LOG` to actually work

chore: Improve rust logging
